#! /bin/zsh
# script to run inference for all models

# AMPK Coccimiglio, cytosol
# NUTS with default init
XLA_FLAGS="--xla_force_host_platform_device_count=1" python inference_pymc.py -model ampk_Coccimiglio -compartment cyto -free_params Km_ADP_pAMPK,k_ADP_pAMPK,Km16,Km_AMP_pAMPK,VmaxkinaseADP,k10r,Km_pAMPK,Km13,Km_ATP_pAMPK,k_AMP_pAMPK,Km17,Vmaxppase,k_ATP_pAMPK,Km15,k11r,k9r,Km14,VmaxppaseATP,Km18,k7r,Km12,k_pAMPK -data_file ../../../Schmitt_et_al_2022_data/fig_2e_cyto.npz -model_info_file ../models/ampk_Coccimiglio.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/ -nwarmup 3000 -nsamples 3000 -nchains 4 -sampler NUTS -lower_mult 1e-2 -upper_mult 1e4 -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 --sample_posterior

# ADVI with mean field approximation
XLA_FLAGS="--xla_force_host_platform_device_count=1" python inference_pymc.py -model ampk_Coccimiglio -compartment cyto -free_params Km_ADP_pAMPK,k_ADP_pAMPK,Km16,Km_AMP_pAMPK,VmaxkinaseADP,k10r,Km_pAMPK,Km13,Km_ATP_pAMPK,k_AMP_pAMPK,Km17,Vmaxppase,k_ATP_pAMPK,Km15,k11r,k9r,Km14,VmaxppaseATP,Km18,k7r,Km12,k_pAMPK -data_file ../../../Schmitt_et_al_2022_data/fig_2e_cyto.npz -model_info_file ../models/ampk_Coccimiglio.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/ -nsamples 4000 -nchains 4 -sampler ADVI -lower_mult 1e-2 -upper_mult 1e4 -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -n_advi_iter 60000 --sample_posterior

# AMPK Coccimiglio, lysosome
# NUTS with default init
XLA_FLAGS="--xla_force_host_platform_device_count=1" python inference_pymc.py -model ampk_Coccimiglio -compartment lyso -free_params Km_ADP_pAMPK,k_ADP_pAMPK,Km16,Km_AMP_pAMPK,VmaxkinaseADP,k10r,Km_pAMPK,Km13,Km_ATP_pAMPK,k_AMP_pAMPK,Km17,Vmaxppase,k_ATP_pAMPK,Km15,k11r,k9r,Km14,VmaxppaseATP,Km18,k7r,Km12,k_pAMPK -data_file ../../../Schmitt_et_al_2022_data/fig_2b_lyso.npz -model_info_file ../models/ampk_Coccimiglio.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/ -nwarmup 3000 -nsamples 3000 -nchains 4 -sampler NUTS -lower_mult 1e-2 -upper_mult 1e4 -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 --sample_posterior

# ADVI with mean field approximation
XLA_FLAGS="--xla_force_host_platform_device_count=1" python inference_pymc.py -model ampk_Coccimiglio -compartment lyso -free_params Km_ADP_pAMPK,k_ADP_pAMPK,Km16,Km_AMP_pAMPK,VmaxkinaseADP,k10r,Km_pAMPK,Km13,Km_ATP_pAMPK,k_AMP_pAMPK,Km17,Vmaxppase,k_ATP_pAMPK,Km15,k11r,k9r,Km14,VmaxppaseATP,Km18,k7r,Km12,k_pAMPK -data_file ../../../Schmitt_et_al_2022_data/fig_2b_lyso.npz -model_info_file ../models/ampk_Coccimiglio.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/ -nsamples 4000 -nchains 4 -sampler ADVI -lower_mult 1e-2 -upper_mult 1e4 -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -n_advi_iter 60000 --sample_posterior

# AMPK Coccimiglio, mitochondria
# NUTS with default init
XLA_FLAGS="--xla_force_host_platform_device_count=1" python inference_pymc.py -model ampk_Coccimiglio -compartment mito -free_params Km_ADP_pAMPK,k_ADP_pAMPK,Km16,Km_AMP_pAMPK,VmaxkinaseADP,k10r,Km_pAMPK,Km13,Km_ATP_pAMPK,k_AMP_pAMPK,Km17,Vmaxppase,k_ATP_pAMPK,Km15,k11r,k9r,Km14,VmaxppaseATP,Km18,k7r,Km12,k_pAMPK -data_file ../../../Schmitt_et_al_2022_data/fig_2c_mito.npz -model_info_file ../models/ampk_Coccimiglio.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/ -nwarmup 3000 -nsamples 3000 -nchains 4 -sampler NUTS -lower_mult 1e-2 -upper_mult 1e4 -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 --sample_posterior

# ADVI with mean field approximation
XLA_FLAGS="--xla_force_host_platform_device_count=1" python inference_pymc.py -model ampk_Coccimiglio -compartment mito -free_params Km_ADP_pAMPK,k_ADP_pAMPK,Km16,Km_AMP_pAMPK,VmaxkinaseADP,k10r,Km_pAMPK,Km13,Km_ATP_pAMPK,k_AMP_pAMPK,Km17,Vmaxppase,k_ATP_pAMPK,Km15,k11r,k9r,Km14,VmaxppaseATP,Km18,k7r,Km12,k_pAMPK -data_file ../../../Schmitt_et_al_2022_data/fig_2c_mito.npz -model_info_file ../models/ampk_Coccimiglio.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/ -nsamples 4000 -nchains 4 -sampler ADVI -lower_mult 1e-2 -upper_mult 1e4 -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -n_advi_iter 60000 --sample_posterior