#! /bin/zsh
# script to run inference for all models
# MA single, cytosol
# NUTS with default init
# python inference_kinase_KO_pymc.py -model MM_nonessential -compartment cyto -free_params kOffAMP,kOffADP,kOffATP,kCaMKK,KmCaMKK,kLKB1,KmLKB1,alphaLKB1,kPP,KmPP,alphaPP,betaAMP -data_file ../../../Schmitt_et_al_2022_data/fig_2e_cyto.npz -LKB1_KO_data_file ../../../Schmitt_et_al_2022_data/fig_2e_cyto_LKB1_KD.npz -CaMKK2_KO_data_file ../../../Schmitt_et_al_2022_data/sup_fig_2g_cyto_CaMKK_KD.npz -model_info_file ../models/MM_nonessential.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/kinase_KO/std_dcr -nsamples 1000 -nchains 2 -sampler Pathfinder -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -data_std_max 0.1 --compute_llike # --sample_posterior

# # MA single, lysosome
# python inference_kinase_KO_pymc.py -model MM_nonessential -compartment lyso -free_params kOffAMP,kOffADP,kOffATP,kCaMKK,KmCaMKK,kLKB1,KmLKB1,alphaLKB1,kPP,KmPP,alphaPP,betaAMP -data_file ../../../Schmitt_et_al_2022_data/fig_2b_lyso.npz -LKB1_KO_data_file ../../../Schmitt_et_al_2022_data/fig_2f_lyso_LKB1_KD.npz -CaMKK2_KO_data_file ../../../Schmitt_et_al_2022_data/sup_fig_2g_lyso_CaMKK_KD.npz -model_info_file ../models/MM_nonessential.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/kinase_KO/std_dcr -nsamples 1000 -nchains 2 -sampler Pathfinder -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -data_std_max 0.1 --compute_llike # --sample_posterior

# # MA single, mitochondria
# python inference_kinase_KO_pymc.py -model MM_nonessential -compartment mito -free_params kOffAMP,kOffADP,kOffATP,kCaMKK,KmCaMKK,kLKB1,KmLKB1,alphaLKB1,kPP,KmPP,alphaPP,betaAMP -data_file ../../../Schmitt_et_al_2022_data/fig_2c_mito.npz -LKB1_KO_data_file ../../../Schmitt_et_al_2022_data/fig_2g_mito_LKB1_KD.npz -CaMKK2_KO_data_file ../../../Schmitt_et_al_2022_data/sup_fig_2g_mito_CaMKK_KD.npz -model_info_file ../models/MM_nonessential.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/kinase_KO/std_dcr -nsamples 1000 -nchains 2 -sampler Pathfinder -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -data_std_max 0.1 --compute_llike # --sample_posterior

python inference_kinase_KO_independent_pymc.py -model MM_nonessential -compartment cyto -free_params kOffAMP,kOffADP,kOffATP,kCaMKK,KmCaMKK,kLKB1,KmLKB1,alphaLKB1,kPP,KmPP,alphaPP,betaAMP -data_file ../../../Schmitt_et_al_2022_data/fig_2e_cyto.npz -LKB1_KO_data_file ../../../Schmitt_et_al_2022_data/fig_2e_cyto_LKB1_KD.npz -CaMKK2_KO_data_file ../../../Schmitt_et_al_2022_data/sup_fig_2g_cyto_CaMKK_KD.npz -model_info_file ../models/MM_nonessential.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/kinase_KO/std_dcr_indep -nsamples 1000 -nchains 2 -sampler Pathfinder -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -data_std_max 0.1 --compute_llike --sample_posterior

# MA single, lysosome
python inference_kinase_KO_independent_pymc.py -model MM_nonessential -compartment lyso -free_params kOffAMP,kOffADP,kOffATP,kCaMKK,KmCaMKK,kLKB1,KmLKB1,alphaLKB1,kPP,KmPP,alphaPP,betaAMP -data_file ../../../Schmitt_et_al_2022_data/fig_2b_lyso.npz -LKB1_KO_data_file ../../../Schmitt_et_al_2022_data/fig_2f_lyso_LKB1_KD.npz -CaMKK2_KO_data_file ../../../Schmitt_et_al_2022_data/sup_fig_2g_lyso_CaMKK_KD.npz -model_info_file ../models/MM_nonessential.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/kinase_KO/std_dcr_indep -nsamples 1000 -nchains 2 -sampler Pathfinder -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -data_std_max 0.1 --compute_llike --sample_posterior

# MA single, mitochondria
python inference_kinase_KO_independent_pymc.py -model MM_nonessential -compartment mito -free_params kOffAMP,kOffADP,kOffATP,kCaMKK,KmCaMKK,kLKB1,KmLKB1,alphaLKB1,kPP,KmPP,alphaPP,betaAMP -data_file ../../../Schmitt_et_al_2022_data/fig_2c_mito.npz -LKB1_KO_data_file ../../../Schmitt_et_al_2022_data/fig_2g_mito_LKB1_KD.npz -CaMKK2_KO_data_file ../../../Schmitt_et_al_2022_data/sup_fig_2g_mito_CaMKK_KD.npz -model_info_file ../models/MM_nonessential.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -savedir ../../../results/param_est/kinase_KO/std_dcr_indep -nsamples 1000 -nchains 2 -sampler Pathfinder -pcoeff 0.3 -icoeff 0.4 -rtol 1e-6 -atol 1e-6 -data_std_max 0.1 --compute_llike --sample_posterior