#!/bin/csh
#PBS -q home-hopper
#PBS -N GSA_MA_single
#PBS -l nodes=1:ppn=64:rack13
#PBS -l walltime=02:00:00
#PBS -e /oasis/tscc/scratch/nlinden/AMPK/err_GSA_MA_double.txt
#PBS -o /oasis/tscc/scratch/nlinden/AMPK/out_GSA_MA_double.txt
#PBS -V
#PBS -M nlinden@ucsd.edu
#PBS -m abe
#PBS -A rangamani-hopper
cd /home/nlinden/AMPK/src/ampk_models/global_sensitivity_analysis
/home/nlinden/mambaforge/envs/pymc5_env/bin/python GSA_MA_double_mech.py /oasis/tscc/scratch/nlinden/AMPK/
exit 0