#!/bin/bash
#SBATCH --job-name  gsa-ma-single-noSensor   
#SBATCH --output slurm-%j.out-%N            # Standard output file
#SBATCH --output slurm-%j.err-%N        # Optional, for separating standard error
#SBATCH --partition rtx3090                                   # Partition name
#SBATCH --qos condo-gpu                                          # QOS name
#SBATCH --nodes 1                                            # Number of nodes
#SBATCH --ntasks 7                                           # Total number of tasks
#SBATCH --gpus=1                                # Number of GPUS needed
#SBATCH --account csd786                       # Allocation name
#SBATCH --export=ALL                       #Optional, Export all environment variables
#SBATCH --time 08:00:00                                     # Walltime limit
#SBATCH --mail-type END                       #Optional, Send mail when the job ends
#SBATCH --mail-user nlinden@ucsd.edu                #Optional, Send mail to this address

# change to GSA dir
cd /tscc/nfs/home/nlinden/AMPK/src/ampk_models/global_sensitivity_analysis/

# mkdir for results
mkdir -p /tscc/lustre/ddn/scratch/nlinden/ampk/MA_single_noSensor/

# run sampling
/tscc/nfs/home/nlinden/miniforge3/envs/pymc/bin/python GSA_sampling.py -model MA_single -free_params kOffAMP,kOffADP,kOffATP,kOffCaMKK,kPhosCaMKK,kOffLKB1,kPhosLKB1,kOffPP,kDephosPP -model_info_file ../models/MA_single_noSensor.json -metab_params_file ../models/metabolism_params_Coccimiglio.json -nsamples 4096 -gsa_method sobol -savedir /tscc/lustre/ddn/scratch/nlinden/ampk/MA_single/no_Sensor_ -tmax 1800

# rsync results to Engram via Cortex
rsync -av /tscc/lustre/ddn/scratch/nlinden/ampk/MA_single_noSensor cortex:/net/engram/nlinden/AMPK/results/GSA/
