#!/bin/bash
#SBATCH --job-name  gsa-ma-single   
#SBATCH --output slurm-%j.out-%N            # Standard output file
#SBATCH --output slurm-%j.err-%N        # Optional, for separating standard error
#SBATCH --partition rtx3090                                   # Partition name
#SBATCH --qos condo-gpu                                          # QOS name
#SBATCH --nodes 1                                            # Number of nodes
#SBATCH --ntasks 7                                           # Total number of tasks
#SBATCH --gpus=1                                # Number of GPUS needed
#SBATCH --account csd786                       # Allocation name
#SBATCH --export=ALL                       #Optional, Export all environment variables
#SBATCH --time 08:00:00                                     # Walltime limit
#SBATCH --mail-type END                       #Optional, Send mail when the job ends
#SBATCH --mail-user nlinden@ucsd.edu                #Optional, Send mail to this address

# change to GSA dir
cd /tscc/nfs/home/nlinden/AMPK/src/ampk_models/global_sensitivity_analysis/

# run sampling
/tscc/nfs/home/nlinden/miniforge3/envs/pymc/bin/python GSA_sampling.py -model MA_single -free_params kOffAMP,kOffADP,kOffATP,kOffCaMKK,kPhosCaMKK,kOffLKB1,kPhosLKB1,kOffPP,kDephosPP,kOffAMPK,kPhosAMPK,kOffPP1,kDephosPP1 -model_info_file ../odes/MA_single.json -upper_mult 1e2 -lower_mult 1e-2 -metab_params_file ../odes/metabolism_params_Coccimiglio.json -nsamples 4096 -gsa_method sobol -savedir /tscc/lustre/ddn/scratch/nlinden/ampk/ -tmax 1e4
