#!/bin/bash
#SBATCH --job-name  gsa-ampk_Coccimiglio   
#SBATCH --output slurm-%j.out-%N            # Standard output file
#SBATCH --output slurm-%j.err-%N        # Optional, for separating standard error
#SBATCH --partition rtx3090                                   # Partition name
#SBATCH --qos condo-gpu                                          # QOS name
#SBATCH --nodes 1                                            # Number of nodes
#SBATCH --ntasks 7                                           # Total number of tasks
#SBATCH --gpus=1                                # Number of GPUS needed
#SBATCH --account csd786                       # Allocation name
#SBATCH --export=ALL                       #Optional, Export all environment variables
#SBATCH --time 08:00:00                                     # Walltime limit
#SBATCH --mail-type END                       #Optional, Send mail when the job ends
#SBATCH --mail-user nlinden@ucsd.edu                #Optional, Send mail to this address

# change to GSA dir
cd /tscc/nfs/home/nlinden/AMPK/src/ampk_models/global_sensitivity_analysis/

# run sampling
/tscc/nfs/home/nlinden/miniforge3/envs/pymc/bin/python GSA_sampling.py -model ampk_Coccimiglio -free_params k6r,k7r,k8r,k9r,k10r,k11r,Km12,Km13,Km14,Km15,Km16,Km17,Km18,Km19,Vmaxkinase,VmaxkinaseATP,VmaxkinaseADP,VmaxkinaseAMP,Vmaxppase,VmaxppaseATP,VmaxppaseADP,VmaxppaseAMP,Km_pAMPK,k_pAMPK,Km_AMP_pAMPK,k_AMP_pAMPK,Km_ADP_pAMPK,k_ADP_pAMPK,Km_ATP_pAMPK,k_ATP_pAMPK -model_info_file ../odes/ampk_Coccimiglio.json -upper_mult 1e2 -lower_mult 1e-2 -metab_params_file ../odes/metabolism_params_Coccimiglio.json -nsamples 4096 -gsa_method sobol -savedir /tscc/lustre/ddn/scratch/nlinden/ampk/ -tmax 5e5
